#!/usr/bin/env node
//
// ledger.mjs — one file per held skill, for the facts that live in neither the
// skill nor a matter of taste.
//
//   node scripts/ledger.mjs --check              regenerate the derivable fields
//                                                 for every held skill, diff
//                                                 against ledger/<name>.json,
//                                                 exit non-zero on any mismatch
//   node scripts/ledger.mjs --check --no-install  the same, but install is not
//                                                 diffed — see the note below
//   node scripts/ledger.mjs --backfill            write ledger/<name>.json for
//                                                 every held skill that lacks one
//   node scripts/ledger.mjs --backfill --force    rewrite every held skill's
//                                                 structural fields (origin,
//                                                 integrity, audit, contract,
//                                                 install), preserving usage
//   node scripts/ledger.mjs --json                print what --check computed,
//                                                 write nothing
//
// This is the schema, and the only three callers that may produce a ledger
// entry: promote.mjs, at the moment a skill lands in skills/; usage.mjs,
// each time it re-measures invocations; and refresh.mjs (SK-34), each time
// it checks whether an acquired skill's upstream has moved — the only
// writer of origin.upstreamHead and the only one of the three that reaches
// the network. All three import writeLedgerSections from here rather than
// writing ledger/<name>.json themselves — one shape, one writer, checked by
// --check so a hand edit cannot reach main.
//
// ---------------------------------------------------------------- the shape
//
// {
//   origin:   { kind: "authored" | "acquired",
//               source: string | null,        // URL; null for authored
//               commit: string | null,         // resolved commit; null if never recorded
//               date: string | null,           // arrival/promotion date, ISO
//               upstreamHead: string | null,  // last commit checked against upstream;
//                                               // null means never checked (SK-34)
//               license: string | null,        // SPDX-ish id read from the upstream's own
//                                               // LICENSE at the commit that was taken
//               licenseBasis: string | null }  // HOW that is known: "pin" when read at the
//                                               // resolved commit, "fetch-window" when the
//                                               // pin was never recorded and the licence is
//                                               // bounded by upstream's own licence history,
//                                               // null when nothing establishes it
//   integrity: { fileCount: number,
//                files: { "<relpath>": "<sha256>" },
//                lastVerified: string | null }  // ISO date this block was written
//   audit:    { verdict: "ADOPT" | "REVISE" | null,
//               counts: { findings: number } | null,
//               dispositioned: boolean | null,
//               reportPath: string | null }
//   contract: { modelInvocable: boolean,
//               descBytes: number,
//               stages: number,
//               gated: boolean | null,          // null if there are no stages to gate
//               tests: { files: number, hasSelfTest: boolean } | null }  // null: no scripts/
//   install:  { symlinked: boolean, path: string | null }   // ~/.claude/skills/<name>
//   usage:    { invocations: { d7, d30, d90, all }, lastInvoked: string | null } | null
// }
//
// origin.date, origin.upstreamHead, integrity.lastVerified, install and usage
// are NOT regenerated by --check — they are point-in-time facts or live
// external state, not values derivable from what skills/<name>/ currently
// holds. Everything else is: --check recomputes it fresh from disk and
// refuses on a mismatch, exactly the "hand-edited ledger file cannot reach
// main" gate this ticket asks for. install IS diffed, but against the live
// filesystem (~/.claude/skills), not against skills/<name>/ — a different
// authoritative source, still derivable, still checked.
//
// That live filesystem does not exist on every machine this runs on, though
// — a CI runner never symlinks anything into ~/.claude/skills, because
// install.sh has no reason to run there. --no-install skips the install
// section of the diff for exactly that case — a gate that only passes on
// one machine is not a gate. check.mjs passes it so the automated gate
// stays identical between CI and a session; running `ledger.mjs --check`
// by hand, with no flag, still checks install — "did I forget to
// re-install this skill" is a real question on a machine that has ever
// run install.sh.
//
// null is a real value throughout. Nothing here is guessed to fill a gap —
// an unrecorded commit stays null rather than being mined out of prose that
// happens to mention a hex string.
//
// Plain Node, no dependencies, in keeping with AUTHORING.md.

import { createHash } from 'node:crypto'
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, readlinkSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { realpathSync } from 'node:fs'

// The library root. Every reader here takes it as an optional argument
// defaulting to this constant, so the module still behaves exactly as it did
// when nobody passes one — but a caller that knows which library it means can
// now say so. SK-86 measured why that matters: `refresh` run from a foreign
// working directory refreshed *this* tree and said nothing, and ten ledger
// entries were written before anyone noticed. A root that can only be inferred
// from a script's own location is a root nobody can redirect.
// ── the library ─────────────────────────────────────────────────────────────
//
// SK-97. Until the split this was `dirname(...)` of this file's own location,
// because the tool lived inside the one library it would ever act on. It does
// not any more, so the root cannot be inferred from where this script sits —
// it is named, or it is the working directory, and either way it is a thing
// the caller can see and change.
function resolveLibrary(argv = process.argv.slice(2)) {
	const i = argv.indexOf('--library')
	if (i !== -1) {
		const value = argv[i + 1]
		if (!value || value.startsWith('--')) {
			console.error('refused: --library needs a directory')
			process.exit(2)
		}
		return resolve(value)
	}
	return resolve(process.env.SKILL_LIBRARY ?? process.cwd())
}

export const LIBRARY = resolveLibrary()
export const SKILLS_DIR = join(LIBRARY, 'skills')
export const LEDGER_DIR = join(LIBRARY, 'ledger')

// ------------------------------------------------------------ frontmatter + stages
//
// Deliberately re-implemented rather than imported from a sibling. Every
// script in this repo that reads a SKILL.md parses it itself — the same
// choice audit-skill.mjs and check-catalog.mjs each made — because a shared
// parsing module is a dependency between scripts that otherwise run
// independently, and AUTHORING.md's "no dependencies" is about more than npm.

function parseFrontmatter(text) {
	if (!text.startsWith('---')) return {}
	const end = text.indexOf('\n---', 3)
	if (end === -1) return {}
	const out = {}
	for (const line of text.slice(4, end).split('\n')) {
		const colon = line.indexOf(':')
		if (colon === -1 || /^\s/.test(line)) continue
		const key = line.slice(0, colon).trim()
		let value = line.slice(colon + 1).trim()
		if (!key) continue
		out[key] = value.replace(/^["']|["']$/g, '')
	}
	return out
}

const STAGE_PATTERNS = [
	/^###\s+(\d+)\s*·\s*(.+?)(?:\s*→\s*(.+))?$/,
	/^###\s+(\d+)\.\s+(.+)$/,
	/^###\s+Phase\s+(\d+)\s*[—–-]\s*(.+)$/,
	/^###\s+Part\s+(\d+)\s*[—–-]\s*(.+)$/
]

function parseStages(text) {
	const lines = text.split('\n')
	const stages = []
	for (let i = 0; i < lines.length; i++) {
		let match = null
		for (const pattern of STAGE_PATTERNS) {
			match = pattern.exec(lines[i])
			if (match) break
		}
		if (!match) continue
		let gate = ''
		for (let j = i + 1; j < lines.length && !/^#{2,3}\s/.test(lines[j]); j++) {
			if (/^>\s*\*\*Gate:\*\*/.test(lines[j])) {
				gate = lines[j].replace(/^>\s*\*\*Gate:\*\*\s*/, '').trim()
				break
			}
		}
		stages.push({ gate })
	}
	return stages
}

// ------------------------------------------------------------------- integrity

// Same walk() promote.mjs uses: lstat, not stat, so a broken symlink is
// skipped rather than crashing the gate; a symlink's target is not this
// artefact's bytes.
function walk(dir, root = dir, acc = []) {
	for (const e of readdirSync(dir)) {
		const abs = join(dir, e)
		const st = lstatSync(abs)
		if (st.isSymbolicLink()) continue
		if (st.isDirectory()) walk(abs, root, acc)
		else acc.push(relative(root, abs))
	}
	return acc
}

const sha256 = (p) => createHash('sha256').update(readFileSync(p)).digest('hex')

export function computeIntegrity(skillDir) {
	const files = {}
	for (const rel of walk(skillDir).sort()) files[rel] = sha256(join(skillDir, rel))
	return { fileCount: Object.keys(files).length, files, lastVerified: null }
}

// ------------------------------------------------------------------- contract

function computeContract(skillDir) {
	const text = readFileSync(join(skillDir, 'SKILL.md'), 'utf8')
	const fm = parseFrontmatter(text)
	const stages = parseStages(text)
	const scriptsDir = join(skillDir, 'scripts')
	let tests = null
	if (existsSync(scriptsDir)) {
		const present = readdirSync(scriptsDir)
		tests = {
			files: present.filter((f) => f.endsWith('.test.mjs')).length,
			hasSelfTest: present.includes('self-test.mjs')
		}
	}
	return {
		modelInvocable: String(fm['disable-model-invocation']).toLowerCase() !== 'true',
		descBytes: Buffer.byteLength(fm.description ?? '', 'utf8'),
		stages: stages.length,
		gated: stages.length === 0 ? null : stages.every((s) => s.gate.length > 0),
		tests
	}
}

// ---------------------------------------------------------------------- origin

// Two record shapes hold this, and neither is authoritative for every held
// skill: `grilling` is the only one with a real ORIGIN.md (skill-intake's own
// convention); five older acquisitions carry the same facts inline in
// AUDIT.md, from before that convention existed. Tried in that order; a field
// neither carries stays null rather than being mined out of the prose that
// mentions it — `animate/AUDIT.md` says "Pinned to `de33dbe`" in a sentence,
// not a table row, and turning that into a regex is exactly the kind of
// fragile inference the "never guessed" rule exists to rule out.
function firstMatch(text, res) {
	for (const re of res) {
		const m = re.exec(text)
		if (m) return m[1].trim()
	}
	return null
}

function computeOrigin(skillDir) {
	const originPath = join(skillDir, 'ORIGIN.md')
	const auditPath = join(skillDir, 'AUDIT.md')
	const hasOrigin = existsSync(originPath)
	const hasAudit = existsSync(auditPath)

	// An authored skill's terms are this repository's terms, so the licence is
	// read from the skill's own frontmatter — the one case SK-82 left open, on
	// the grounds that a `license:` line is the author's own declaration and
	// this repository is the author here. Null when a skill has not declared
	// one: unknown is the honest answer, and it is not a claim of permission.
	if (!hasAudit) {
		const fm = parseFrontmatter(readFileSync(join(skillDir, 'SKILL.md'), 'utf8'))
		const declared = fm.license?.trim() || null
		return {
			kind: 'authored', source: null, commit: null, date: null, upstreamHead: null,
			license: declared,
			licenseBasis: declared ? 'declared — the skill is this repository\'s own, under its root LICENSE' : null
		}
	}

	const originText = hasOrigin ? readFileSync(originPath, 'utf8') : ''
	const auditText = readFileSync(auditPath, 'utf8')

	// Both branches strip the backticks intake.mjs may have written around the
	// source. It formats a local path as inline code and a remote URL bare, so
	// this pattern used to capture ``/path/to/src`` verbatim for every
	// path-sourced skill, and refresh then fetched a repository whose name
	// began with a backtick. The AUDIT.md branch below had always stripped
	// them; the fixtures write the URL form, so the two never disagreed in a
	// test. Backticks cannot occur inside a real source, so excluding them from
	// the capture is safe in both.
	const source = firstMatch(originText, [/\|\s*\*\*Source\*\*\s*\|\s*`?([^\n|`]+?)`?\s*\|/]) ??
		firstMatch(auditText, [/\|\s*\*\*Source\*\*\s*\|\s*`?([^\n|`]+?)`?(?:\s*→[^\n|]*)?\s*\|/])

	const commit = firstMatch(originText, [/\*\*Resolved commit\*\*\s*\|\s*`([0-9a-f]{7,40})`/i]) ??
		firstMatch(auditText, [/\*\*Upstream commit\*\*\s*\|\s*`([0-9a-f]{7,40})`/i])

	const date = firstMatch(originText, [/\|\s*\*\*Fetched\*\*\s*\|\s*(\d{4}-\d{2}-\d{2})/]) ??
		firstMatch(auditText, [/\|\s*\*\*Retrieved\*\*\s*\|\s*(\d{4}-\d{2}-\d{2})/])

	// The licence is a fact about the commit that was taken, not about upstream
	// today — SK-82 decided that, and SK-91 measured why it matters: at
	// `apple-design`'s pinned commit the upstream LICENSE named a different
	// copyright holder than it does now. So it is read out of ORIGIN.md, beside
	// the pin, where the two cannot drift apart.
	const license = firstMatch(originText, [/\|\s*\*\*License\*\*\s*\|\s*`?([A-Za-z0-9.+-]+?)`?\s*(?:\||$)/]) ??
		firstMatch(auditText, [/\|\s*\*\*License\*\*\s*\|\s*`?([A-Za-z0-9.+-]+?)`?\s*(?:\||$)/])

	// The basis is read from wherever the licence was read from — ORIGIN.md for
	// anything `skill-intake` fetched, AUDIT.md for the five that predate it.
	// Defaulting to "pin" when neither states one would assert that the licence
	// was read at the resolved commit, which for four of these is false: they
	// were cloned --depth 1 and no commit was ever recorded.
	const licenseBasis = license === null
		? null
		: (firstMatch(originText, [/\|\s*\*\*Licence basis\*\*\s*\|\s*([^\n|]+?)\s*\|/]) ??
			firstMatch(auditText, [/\|\s*\*\*Licence basis\*\*\s*\|\s*([^\n|]+?)\s*\|/]))

	return { kind: 'acquired', source, commit, date, upstreamHead: null, license, licenseBasis }
}

// ---------------------------------------------------------------------- audit

// The findings-table row shape promote.mjs's readAudit already parses:
// `| # | Code | Location | Disposition | Reason |`. Not every AUDIT.md has
// one — apple-design's says "no findings" in prose — so counts and
// dispositioned are null rather than zero when there is nothing to count;
// zero would claim a table was read and came up empty, which is a different
// fact from there being no table.
const DISPOSITIONS = /^(real|accepted|false positive|fixed|removed|n\/a)\b/i

function computeAudit(skillDir) {
	const path = join(skillDir, 'AUDIT.md')
	if (!existsSync(path)) return { verdict: null, counts: null, dispositioned: null, reportPath: null }
	const text = readFileSync(path, 'utf8')

	const verdict = /\|\s*\*\*Verdict\*\*\s*\|[\s*]*(ADOPT|REVISE|REJECT)\b/i.exec(text)?.[1]?.toUpperCase() ?? null

	let findings = 0
	let dispositionedCount = 0
	let sawTable = false
	for (const line of text.split('\n')) {
		const m = /^\|\s*\d+\s*\|\s*`?([A-Z]+-[A-Z0-9]+)`?\s*\|([^|]*)\|([^|]*)\|/.exec(line)
		if (!m) continue
		sawTable = true
		findings++
		if (DISPOSITIONS.test(m[3].trim())) dispositionedCount++
	}

	return {
		verdict,
		counts: sawTable ? { findings } : null,
		dispositioned: sawTable ? dispositionedCount === findings : null,
		reportPath: `skills/${relative(SKILLS_DIR, skillDir)}/AUDIT.md`
	}
}

// --------------------------------------------------------------------- install

// Read-only against a directory outside this repo. Legitimate: nothing here
// writes there, and "is this symlinked in" is exactly the live fact neither
// skills/<name>/ nor catalog.json can answer.
export function computeInstall(name) {
	const linkPath = join(homedir(), '.claude', 'skills', name)
	if (!existsSync(linkPath)) return { symlinked: false, path: null }
	try {
		const st = lstatSync(linkPath)
		if (!st.isSymbolicLink()) return { symlinked: false, path: null }
		return { symlinked: true, path: readlinkSync(linkPath) }
	} catch {
		return { symlinked: false, path: null }
	}
}

// ----------------------------------------------------------- the full structural block

// Everything --check can regenerate and diff: origin.kind/source/commit,
// integrity.fileCount/files, audit.*, contract.*, install. Excludes
// origin.date, origin.upstreamHead, integrity.lastVerified and usage — see
// the header comment for why each is excluded.
export function computeStructural(skillDir, name) {
	return {
		origin: computeOrigin(skillDir),
		integrity: computeIntegrity(skillDir),
		audit: computeAudit(skillDir),
		contract: computeContract(skillDir),
		install: computeInstall(name)
	}
}

// ------------------------------------------------------------------ read / write

export function ledgerPath(name, root = LIBRARY) {
	return join(root, 'ledger', `${name}.json`)
}

export function readLedger(name, root = LIBRARY) {
	const path = ledgerPath(name, root)
	if (!existsSync(path)) return null
	return JSON.parse(readFileSync(path, 'utf8'))
}

const EMPTY_ENTRY = {
	origin: { kind: null, source: null, commit: null, date: null, upstreamHead: null, license: null, licenseBasis: null },
	integrity: { fileCount: 0, files: {}, lastVerified: null },
	audit: { verdict: null, counts: null, dispositioned: null, reportPath: null },
	contract: { modelInvocable: null, descBytes: null, stages: null, gated: null, tests: null },
	install: { symlinked: false, path: null },
	usage: null
}

// Read-merge-write, so promote.mjs writing `origin` through `install` and
// usage.mjs writing `usage` (and refreshing `install`, the one section both
// touch — see usage.mjs) can never clobber a section the other one owns.
// `sections` merges shallowly at the top level only; each value replaces its
// whole key, never merges into it.
export function writeLedgerSections(name, sections, root = LIBRARY) {
	mkdirSync(join(root, 'ledger'), { recursive: true })
	const current = readLedger(name, root) ?? EMPTY_ENTRY
	const next = { ...current, ...sections }
	writeFileSync(ledgerPath(name, root), JSON.stringify(next, null, 2) + '\n')
	return next
}

// Writes every structural section in one call — what promote.mjs and the
// backfill both do, since both are producing a whole fresh entry rather than
// updating the one field usage.mjs owns. usage.mjs's own section is never
// part of `sections`, so writeLedgerSections leaves it untouched either way.
export function writeStructural(name, skillDir, { date = null } = {}, root = LIBRARY) {
	const structural = computeStructural(skillDir, name)
	structural.origin.date = date
	structural.integrity.lastVerified = new Date().toISOString().slice(0, 10)
	return writeLedgerSections(name, structural, root)
}

// ------------------------------------------------------------------- held skills

export function heldSkills(root = LIBRARY) {
	const dir = join(root, 'skills')
	if (!existsSync(dir)) return []
	return readdirSync(dir)
		.filter((n) => !n.startsWith('.'))
		.filter((n) => existsSync(join(dir, n, 'SKILL.md')))
		.sort()
}

// ------------------------------------------------------------------------ check

// Diffs only the fields computeStructural can regenerate from disk — deep
// value equality via JSON.stringify on sorted keys is enough here, since
// every field is a plain string/number/boolean/plain object with no key
// order guarantee worth trusting; sorting keys first makes the comparison
// order-independent without writing a structural differ.
function stableStringify(v) {
	if (Array.isArray(v)) return `[${v.map(stableStringify).join(',')}]`
	if (v && typeof v === 'object') {
		return `{${Object.keys(v)
			.sort()
			.map((k) => `${JSON.stringify(k)}:${stableStringify(v[k])}`)
			.join(',')}}`
	}
	return JSON.stringify(v)
}

export function checkAll({ noInstall = false } = {}) {
	const errors = []
	const held = new Set(heldSkills())
	const sections = noInstall
		? ['origin', 'integrity', 'audit', 'contract']
		: ['origin', 'integrity', 'audit', 'contract', 'install']

	for (const name of held) {
		const onDisk = readLedger(name)
		if (!onDisk) {
			errors.push(`${name}: no ledger/${name}.json for a held skill`)
			continue
		}
		const fresh = computeStructural(join(SKILLS_DIR, name), name)
		for (const section of sections) {
			const onDiskValue = { ...(onDisk[section] ?? {}) }
			const freshValue = { ...(fresh[section] ?? {}) }
			// Point-in-time fields inside otherwise-diffed sections: carried
			// through unchanged rather than compared, exactly as the header says.
			if (section === 'origin') {
				freshValue.date = onDiskValue.date
				freshValue.upstreamHead = onDiskValue.upstreamHead
			}
			if (section === 'integrity') freshValue.lastVerified = onDiskValue.lastVerified
			if (stableStringify(onDiskValue) !== stableStringify(freshValue)) {
				errors.push(`${name}: ledger .${section} does not match what is on disk now`)
			}
		}
	}

	// usage.json is SK-10's aggregate across every skill, not a per-skill
	// entry — the one filename in this directory that is exempt from naming a
	// held skill, because it never claimed to.
	if (existsSync(LEDGER_DIR)) {
		for (const f of readdirSync(LEDGER_DIR)) {
			if (!f.endsWith('.json') || f === 'usage.json') continue
			const name = f.slice(0, -'.json'.length)
			if (!held.has(name)) errors.push(`ledger/${f}: no held skill named "${name}" — orphaned ledger entry`)
		}
	}

	return errors
}

// ---------------------------------------------------------------------- backfill

export function backfill({ force = false } = {}) {
	const written = []
	const skipped = []
	for (const name of heldSkills()) {
		if (!force && readLedger(name)) {
			skipped.push(name)
			continue
		}
		const skillDir = join(SKILLS_DIR, name)
		const fresh = computeStructural(skillDir, name)
		fresh.integrity.lastVerified = new Date().toISOString().slice(0, 10)
		// A backfill has no promotion moment to read a date from. Where the
		// record names an arrival date, that is used — it is a real fact, not a
		// guess. Where nothing records one (the three pre-pipeline skills, and
		// any authored skill promoted before a date was thought to matter),
		// it stays null rather than being invented from today or from git log,
		// which was not run and would assert a check that never happened for
		// the same reason `upstreamHead` stays null.
		writeLedgerSections(name, fresh)
		written.push(name)
	}
	return { written, skipped }
}

// -------------------------------------------------------------------------- main

function invokedAsScript() {
	if (!process.argv[1]) return false
	try {
		return realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))
	} catch {
		return false
	}
}

function main(argv) {
	const CHECK = argv.includes('--check')
	const BACKFILL = argv.includes('--backfill')
	const FORCE = argv.includes('--force')
	const JSON_OUT = argv.includes('--json')
	const NO_INSTALL = argv.includes('--no-install')
	const WRITE_STRUCTURAL = argv.includes('--write-structural')
	const rootAt = argv.indexOf('--library')
	const ROOT = rootAt !== -1 && argv[rootAt + 1] ? resolve(argv[rootAt + 1]) : LIBRARY

	if (BACKFILL) {
		const { written, skipped } = backfill({ force: FORCE })
		if (JSON_OUT) {
			console.log(JSON.stringify({ written, skipped }, null, 2))
		} else {
			console.log(`ledger backfill — ${written.length} written, ${skipped.length} already present`)
			for (const n of written) console.log(`  wrote  ${n}`)
			for (const n of skipped) console.log(`  kept   ${n} (already has a ledger entry; pass --force to rewrite)`)
		}
		return 0
	}

	// One skill's structural sections, written through a process boundary.
	//
	// promote.mjs used to reach `../../../scripts/ledger.mjs` and import this
	// module directly, which is what made `skill-adopt` a repo-coupled skill
	// rather than a portable one (SK-86 finding 1) — installed anywhere else it
	// could not start at all. It already spawns `check-catalog.mjs` as a
	// subprocess; this makes the ledger write the same shape, so the skill
	// reaches nothing outside its own directory and the coupling survives the
	// split as a path that can be missing and named rather than an import that
	// cannot.
	if (WRITE_STRUCTURAL) {
		const name = argv[argv.indexOf('--write-structural') + 1]
		const dirAt = argv.indexOf('--skill-dir')
		const dateAt = argv.indexOf('--date')
		if (!name || name.startsWith('--')) {
			console.error('usage: ledger.mjs --write-structural <name> [--skill-dir <dir>] [--date <iso>] [--library <dir>]')
			return 2
		}
		const skillDir = dirAt !== -1 ? argv[dirAt + 1] : join(ROOT, 'skills', name)
		if (!existsSync(join(skillDir, 'SKILL.md'))) {
			console.error(`refused: ${skillDir} has no SKILL.md`)
			return 2
		}
		const date = dateAt !== -1 ? argv[dateAt + 1] : null
		const entry = writeStructural(name, skillDir, { date }, ROOT)
		if (JSON_OUT) console.log(JSON.stringify(entry, null, 2))
		else console.log(`ledger — wrote ${name}`)
		return 0
	}

	if (CHECK) {
		const errors = checkAll({ noInstall: NO_INSTALL })
		if (JSON_OUT) {
			console.log(JSON.stringify({ errors }, null, 2))
		} else if (errors.length) {
			console.log(`ledger --check — ${errors.length} mismatch(es)`)
			for (const e of errors) console.log(`  ✗ ${e}`)
		} else {
			console.log(`ledger --check — ${heldSkills().length} skill(s), 0 mismatch(es)`)
		}
		return errors.length ? 1 : 0
	}

	console.error('usage: ledger.mjs --check [--no-install] | --backfill [--force] | --write-structural <name> [--skill-dir <dir>] [--date <iso>] [--library <dir>] [--json]')
	return 2
}

if (invokedAsScript()) process.exit(main(process.argv.slice(2)))

export const _url = pathToFileURL(fileURLToPath(import.meta.url)).href
